config/routes.rb
Rails.application.routes.draw do

  root 'welcomes#index'
  resources :frases

  resource :welcome, only: [:index] do
    get :atualizar
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/frase.rb
class Frase < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/frases_controller.rb
class FrasesController < ApplicationController

  before_action :set_frase, only: [:edit, :update, :destroy]

  def new
    @frase = Frase.new
  end

  def create
    @frase = Frase.new frase_params
    @frase.save

    redirect_to root_url
  end

  def index
    @frase = Frase.all
  end

  def edit
  end

  def update
    @frase.update frase_params
  end

  def destroy
    @frase.destroy
  end

  def frase_params
    params.require(:frase).permit :mensagem, :id
  end

  def set_frase
    id = params[:id]
    @frase = Frase.find(id)
  end

end

app/controllers/welcomes_controller.rb
class WelcomesController < ApplicationController

  def index
    @frase = Frase.order("RANDOM()").limit(1).first
  end

  def atualizar
    @frase = Frase.order("RANDOM()").limit(1).first
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/frases/edit.html.erb
<%= form_for @frase do |f| %>

  <div class="form-group">
    <%= f.label :mensagem %>
    <%= f.text_field :mensagem, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.submit %>
  </div>

<% end %>

app/views/frases/index.html.erb
<% @frase.each do |frase| %>
  <%= frase.mensagem %>
  <%= link_to "Alterar", edit_frase_path(frase) %>
  <%= link_to "Remover", frase, method: :delete, remote: true%>
<% end %>

app/views/frases/new.html.erb
<%= form_for @frase do |f| %>

  <div class="form-group">
    <%= f.label :mensagem %>
    <%= f.text_field :mensagem, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.submit %>
  </div>

<% end %>

app/views/frases/show.html.erb
<%= @frase.mensagem %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bisc8dasorte</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/welcomes/atualizar.js.erb
$('#mensagem').html('<%= @frase.mensagem %>');

app/views/welcomes/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>oi</title>
</head>
<body>

<h1>teste</h1>

<div id="mensagem">
  <%= @frase.mensagem %>
</div>


<%= link_to 'Nova Mensagem', new_frase_path %>
<%= link_to 'Atualizar', atualizar_welcome_path, remote: true %>



</body>
</html>